name: cli_windows
description: A sample command-line application with basic argument parsing.
version: 0.0.1

environment:
  sdk: ^3.6.0-326.0.dev

dependencies:
  args: ^2.5.0
  thermion_dart:
    path: ../../../thermion_dart
  ffi: ^2.1.3
  vector_math: ^2.1.4
  native_toolchain_c: ^0.9.0
  native_assets_cli: ^0.12.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0


