name: cli_windows
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-326.0.dev

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  thermion_dart:
    path: F:\Projects\thermion\thermion_dart
  ffi: ^2.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
