#ifndef EDGE_OUTLINE_H_
#define EDGE_OUTLINE_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t EDGE_OUTLINE_PACKAGE[];
    extern int EDGE_OUTLINE_EDGE_OUTLINE_OFFSET;
    extern int EDGE_OUTLINE_EDGE_OUTLINE_SIZE;
}
#define EDGE_OUTLINE_EDGE_OUTLINE_DATA (EDGE_OUTLINE_PACKAGE + EDGE_OUTLINE_EDGE_OUTLINE_OFFSET)

#endif
