#ifndef UNLIT_FIXED_SIZE_WEB_COMBINED_H_
#define UNLIT_FIXED_SIZE_WEB_COMBINED_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
    extern const uint8_t UNLIT_FIXED_SIZE_PACKAGE[];
#ifdef __cplusplus
}
#endif

#define UNLIT_FIXED_SIZE_UNLIT_FIXED_SIZE_OFFSET 0
#define UNLIT_FIXED_SIZE_UNLIT_FIXED_SIZE_SIZE 23143
#define UNLIT_FIXED_SIZE_UNLIT_FIXED_SIZE_DATA (UNLIT_FIXED_SIZE_PACKAGE + UNLIT_FIXED_SIZE_UNLIT_FIXED_SIZE_OFFSET)

#endif
