#ifndef UNLIT_FIXED_SIZE_H_
#define UNLIT_FIXED_SIZE_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t UNLIT_FIXED_SIZE_PACKAGE[];
    extern int UNLIT_FIXED_SIZE_UNLIT_FIXED_SIZE_OFFSET;
    extern int UNLIT_FIXED_SIZE_UNLIT_FIXED_SIZE_SIZE;
}
#define UNLIT_FIXED_SIZE_UNLIT_FIXED_SIZE_DATA (UNLIT_FIXED_SIZE_PACKAGE + UNLIT_FIXED_SIZE_UNLIT_FIXED_SIZE_OFFSET)

#endif
