// Adds typed-data entry points to ffigen's native output. Native signatures and
// argument order are derived from the generated declarations, never duplicated.
import 'dart:io';

const _marker = '// BEGIN GENERATED MATRIX TYPED-DATA WRAPPERS';
const _typedDataImport = "import 'dart:typed_data' as typed_data;";

String generateMatrixTypedDataWrappers(String source) {
  final marker = source.indexOf(_marker);
  if (marker != -1) source = source.substring(0, marker).trimRight() + '\n';
  // ffigen emits each external declaration as one semicolon-terminated block.
  // Bounding the match by semicolons prevents pairing an annotation with a
  // different function, regardless of formatter line breaks or generic nesting.
  final declarations = RegExp(r'@ffi\.Native<[^;]+>\(([^;]*)\)\s*external\s+void\s+(\w+)\s*\(([^;]*)\);');
  final wrappers = <String>[];
  for (final declaration in declarations.allMatches(source)) {
    final parameters = _splitParameters(declaration[3]!);
    final matrixParameters = parameters.where((p) => p.name == 'matrix16' || p.name == 'out16').toList();
    if (matrixParameters.isEmpty) continue;
    final name = declaration[2]!;
    if (!RegExp(r'\bisLeaf\s*:\s*true\b').hasMatch(declaration[1]!)) {
      throw StateError('$name must be a leaf call to borrow typed-data storage');
    }
    for (final parameter in matrixParameters) {
      if (parameter.type.replaceAll(RegExp(r'\s'), '') != 'ffi.Pointer<ffi.Double>') {
        throw StateError('$name.${parameter.name} must point to 16 doubles');
      }
    }
    final borrowedNames = matrixParameters.map((p) => p.name).toSet();
    final wrapper = StringBuffer()
      ..writeln('/// Borrows 16 column-major doubles for the duration of the leaf call.')
      ..writeln('void ${name}TypedData(');
    for (final parameter in parameters) {
      final type = borrowedNames.contains(parameter.name) ? 'typed_data.Float64List' : parameter.type;
      wrapper.writeln('  $type ${parameter.name},');
    }
    wrapper.writeln(') {');
    for (final parameter in matrixParameters) {
      wrapper.writeln(
        "  if (${parameter.name}.length != 16) throw ArgumentError.value(${parameter.name}.length, '${parameter.name}', 'Expected 16 doubles');",
      );
    }
    final arguments = parameters.map((p) => borrowedNames.contains(p.name) ? '${p.name}.address' : p.name).join(', ');
    wrapper
      ..writeln('  $name($arguments);')
      ..writeln('}');
    wrappers.add(wrapper.toString());
  }
  if (wrappers.isEmpty) throw StateError('No matrix16/out16 native buffer declarations found');
  if (!source.contains(_typedDataImport)) {
    const ffiImport = "import 'dart:ffi' as ffi;";
    if (!source.contains(ffiImport)) throw StateError('Expected ffigen dart:ffi import');
    source = source.replaceFirst(ffiImport, '$ffiImport\n$_typedDataImport');
  }
  return '${source.trimRight()}\n\n$_marker\n'
      '// Generated by tool/generate_matrix_typed_data.dart after ffigen.\n'
      '// Keep .address call sites in this library to avoid missing #PT\n'
      '// trampolines when package:test loads kernels.\n\n${wrappers.join('\n')}';
}

List<({String type, String name})> _splitParameters(String source) {
  final parts = <String>[];
  var depth = 0;
  var start = 0;
  for (var i = 0; i < source.length; i++) {
    final char = source[i];
    if ('<([{'.contains(char)) depth++;
    if ('>)]}'.contains(char)) depth--;
    if (depth < 0) throw FormatException('Unbalanced generated parameter list');
    if (char == ',' && depth == 0) {
      parts.add(source.substring(start, i));
      start = i + 1;
    }
  }
  if (depth != 0) throw FormatException('Unbalanced generated parameter list');
  parts.add(source.substring(start));
  return parts.where((part) => part.trim().isNotEmpty).map((part) {
    final match = RegExp(r'^(.+)\s+([\w$]+)$').firstMatch(part.trim().replaceAll(RegExp(r'\s+'), ' '));
    if (match == null) throw FormatException('Unsupported generated parameter: $part');
    return (type: match[1]!, name: match[2]!);
  }).toList();
}

void main(List<String> args) {
  final file = File(args.isEmpty ? 'lib/src/bindings/src/thermion_dart_ffi.g.dart' : args.single);
  file.writeAsStringSync(generateMatrixTypedDataWrappers(file.readAsStringSync()));
}
