#ifndef GLTFRESOURCES_LITE_H_
#define GLTFRESOURCES_LITE_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t GLTFRESOURCES_LITE_PACKAGE[];
    extern int GLTFRESOURCES_LITE_LIT_OPAQUE_OFFSET;
    extern int GLTFRESOURCES_LITE_LIT_OPAQUE_SIZE;
    extern int GLTFRESOURCES_LITE_LIT_FADE_OFFSET;
    extern int GLTFRESOURCES_LITE_LIT_FADE_SIZE;
}
#define GLTFRESOURCES_LITE_LIT_OPAQUE_DATA (GLTFRESOURCES_LITE_PACKAGE + GLTFRESOURCES_LITE_LIT_OPAQUE_OFFSET)
#define GLTFRESOURCES_LITE_LIT_FADE_DATA (GLTFRESOURCES_LITE_PACKAGE + GLTFRESOURCES_LITE_LIT_FADE_OFFSET)

#endif
