#ifndef GLTFRESOURCES_H_
#define GLTFRESOURCES_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t GLTFRESOURCES_PACKAGE[];
    extern int GLTFRESOURCES_LIT_FADE_OFFSET;
    extern int GLTFRESOURCES_LIT_FADE_SIZE;
    extern int GLTFRESOURCES_LIT_OPAQUE_OFFSET;
    extern int GLTFRESOURCES_LIT_OPAQUE_SIZE;
    extern int GLTFRESOURCES_LIT_MASKED_OFFSET;
    extern int GLTFRESOURCES_LIT_MASKED_SIZE;
    extern int GLTFRESOURCES_SPECULARGLOSSINESS_FADE_OFFSET;
    extern int GLTFRESOURCES_SPECULARGLOSSINESS_FADE_SIZE;
    extern int GLTFRESOURCES_SPECULARGLOSSINESS_OPAQUE_OFFSET;
    extern int GLTFRESOURCES_SPECULARGLOSSINESS_OPAQUE_SIZE;
    extern int GLTFRESOURCES_SPECULARGLOSSINESS_MASKED_OFFSET;
    extern int GLTFRESOURCES_SPECULARGLOSSINESS_MASKED_SIZE;
    extern int GLTFRESOURCES_UNLIT_FADE_OFFSET;
    extern int GLTFRESOURCES_UNLIT_FADE_SIZE;
    extern int GLTFRESOURCES_UNLIT_OPAQUE_OFFSET;
    extern int GLTFRESOURCES_UNLIT_OPAQUE_SIZE;
    extern int GLTFRESOURCES_UNLIT_MASKED_OFFSET;
    extern int GLTFRESOURCES_UNLIT_MASKED_SIZE;
    extern int GLTFRESOURCES_LIT_VOLUME_OFFSET;
    extern int GLTFRESOURCES_LIT_VOLUME_SIZE;
    extern int GLTFRESOURCES_LIT_TRANSMISSION_OFFSET;
    extern int GLTFRESOURCES_LIT_TRANSMISSION_SIZE;
    extern int GLTFRESOURCES_LIT_SHEEN_OFFSET;
    extern int GLTFRESOURCES_LIT_SHEEN_SIZE;
}
#define GLTFRESOURCES_LIT_FADE_DATA (GLTFRESOURCES_PACKAGE + GLTFRESOURCES_LIT_FADE_OFFSET)
#define GLTFRESOURCES_LIT_OPAQUE_DATA (GLTFRESOURCES_PACKAGE + GLTFRESOURCES_LIT_OPAQUE_OFFSET)
#define GLTFRESOURCES_LIT_MASKED_DATA (GLTFRESOURCES_PACKAGE + GLTFRESOURCES_LIT_MASKED_OFFSET)
#define GLTFRESOURCES_SPECULARGLOSSINESS_FADE_DATA (GLTFRESOURCES_PACKAGE + GLTFRESOURCES_SPECULARGLOSSINESS_FADE_OFFSET)
#define GLTFRESOURCES_SPECULARGLOSSINESS_OPAQUE_DATA (GLTFRESOURCES_PACKAGE + GLTFRESOURCES_SPECULARGLOSSINESS_OPAQUE_OFFSET)
#define GLTFRESOURCES_SPECULARGLOSSINESS_MASKED_DATA (GLTFRESOURCES_PACKAGE + GLTFRESOURCES_SPECULARGLOSSINESS_MASKED_OFFSET)
#define GLTFRESOURCES_UNLIT_FADE_DATA (GLTFRESOURCES_PACKAGE + GLTFRESOURCES_UNLIT_FADE_OFFSET)
#define GLTFRESOURCES_UNLIT_OPAQUE_DATA (GLTFRESOURCES_PACKAGE + GLTFRESOURCES_UNLIT_OPAQUE_OFFSET)
#define GLTFRESOURCES_UNLIT_MASKED_DATA (GLTFRESOURCES_PACKAGE + GLTFRESOURCES_UNLIT_MASKED_OFFSET)
#define GLTFRESOURCES_LIT_VOLUME_DATA (GLTFRESOURCES_PACKAGE + GLTFRESOURCES_LIT_VOLUME_OFFSET)
#define GLTFRESOURCES_LIT_TRANSMISSION_DATA (GLTFRESOURCES_PACKAGE + GLTFRESOURCES_LIT_TRANSMISSION_OFFSET)
#define GLTFRESOURCES_LIT_SHEEN_DATA (GLTFRESOURCES_PACKAGE + GLTFRESOURCES_LIT_SHEEN_OFFSET)

#endif
