#ifndef IMAGEMATERIALS_IOS_H_
#define IMAGEMATERIALS_IOS_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t IMAGEMATERIALS_IOS_PACKAGE[];
    extern int IMAGEMATERIALS_IOS_IMAGE_FILAMAT_OFFSET;
    extern int IMAGEMATERIALS_IOS_IMAGE_FILAMAT_SIZE;
}
#define IMAGEMATERIALS_IOS_IMAGE_FILAMAT_DATA (IMAGEMATERIALS_IOS_PACKAGE + IMAGEMATERIALS_IOS_IMAGE_FILAMAT_OFFSET)

#endif
