name: thermion_flutter_method_channel
description: Desktop + mobile implementation for texture creation + registration with Flutter.
repository: https://github.com/nmfisher/thermion_flutter/thermion_flutter
version: 0.3.2

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"
flutter:
  plugin:
    implements: thermion_flutter_platform_interface
    platforms:
      ios:
        dartPluginClass: ThermionFlutterMethodChannelPlatform
      android:
        dartPluginClass: ThermionFlutterMethodChannelPlatform
      macos:
        dartPluginClass: ThermionFlutterMethodChannelPlatform
      windows:
        dartPluginClass: ThermionFlutterMethodChannelPlatform

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  thermion_flutter_platform_interface: ^0.3.2
  thermion_dart: ^0.3.2
  logging: ^1.2.0
dependency_overrides:
  thermion_dart:
    path: ../../thermion_dart
  thermion_flutter_platform_interface:
    path: ../thermion_flutter_platform_interface
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
