name: animations
description: "Thermion animation example."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  vector_math: ^2.1.4

  win32: 5.5.1
  web: 1.0.0
  thermion_flutter: ^0.2.1-dev.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  thermion_dart:
    path: ../../../thermion_dart
  thermion_flutter:
    path: ../../../thermion_flutter/thermion_flutter
  thermion_flutter_method_channel:
    path: ../../../thermion_flutter/thermion_flutter_method_channel
  thermion_flutter_platform_interface:
    path: ../../../thermion_flutter/thermion_flutter_platform_interface
  thermion_flutter_web:
    path: ../../../thermion_flutter/thermion_flutter_web

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/BusterDrone/
    - assets/BusterDrone/textures/
