name: 'Setup Build Environment'
description: 'Set up LLVM, MESA, and Flutter for builds'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Setup LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16"
    - name: Add LLVM to PATH
      shell: bash
      run: |
        echo "${{ github.workspace }}/llvm/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=${{ github.workspace }}/llvm/lib/x86_64-unknown-linux-gnu/" >> $GITHUB_ENV
    - name: Verify installation
      shell: bash
      run: clang --version
    - name: Install MESA
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        sudo apt-get install -y libosmesa6-dev
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: master
        architecture: X64
