name: materials_and_textures
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  thermion_flutter:
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  thermion_dart:
    path: ../../../thermion_dart
  thermion_flutter:
    path: ../../../thermion_flutter/thermion_flutter
    
flutter:
  uses-material-design: true
  assets:
    - assets/