#pragma once

#pragma comment(lib, "Shlwapi.lib")
#pragma comment(lib, "opengl32.lib")
#pragma comment(lib, "gdi32.lib")
#pragma comment(lib, "user32.lib")
#pragma comment(lib, "shell32.lib")
#pragma comment(lib, "dwmapi.lib")
#pragma comment(lib, "comctl32.lib")
#pragma comment(lib, "filament.lib")
#pragma comment(lib, "bluevk.lib")
#pragma comment(lib, "bluegl.lib")
#pragma comment(lib, "backend.lib")
#pragma comment(lib, "filamat.lib")
// The .mat parser for runtime material compilation (Engine_compileMaterial).
// matp must precede utils.lib in link order (it references utils symbols);
// unlike the Linux/macOS archives, the Windows filamat/matp do not bundle
// glslang/SPIRV, so the shader-compiler libraries they reference are linked
// here explicitly.
#pragma comment(lib, "matp.lib")
#pragma comment(lib, "glslang.lib")
#pragma comment(lib, "SPIRV.lib")
#pragma comment(lib, "SPIRV-Tools.lib")
#pragma comment(lib, "SPIRV-Tools-opt.lib")
#pragma comment(lib, "spirv-cross-core.lib")
#pragma comment(lib, "spirv-cross-glsl.lib")
#pragma comment(lib, "spirv-cross-msl.lib")
#pragma comment(lib, "geometry.lib")
#pragma comment(lib, "utils.lib")
#pragma comment(lib, "filabridge.lib")
#pragma comment(lib, "gltfio_core.lib")
#pragma comment(lib, "filament-iblprefilter.lib")
#pragma comment(lib, "image.lib")
#pragma comment(lib, "imageio.lib")
#pragma comment(lib, "tinyexr.lib")
#pragma comment(lib, "filaflat.lib")
#pragma comment(lib, "dracodec.lib")
#pragma comment(lib, "ibl.lib")
#pragma comment(lib, "ktxreader.lib")
#pragma comment(lib, "z.lib")
#pragma comment(lib, "stb.lib")
#pragma comment(lib, "uberzlib.lib")
#pragma comment(lib, "smol-v.lib")
#pragma comment(lib, "uberarchive.lib")
#pragma comment(lib, "zstd.lib")
#pragma comment(lib, "basis_transcoder.lib")
#pragma comment(lib, "meshoptimizer.lib")
#pragma comment(lib, "vulkan-1.lib")
#pragma comment(lib, "dxgi.lib")
#pragma comment(lib, "d3d11.lib")
#pragma comment(lib, "mikktspace.lib")
 
