#ifndef ROTATION_GIZMO_GLB_H_
#define ROTATION_GIZMO_GLB_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t ROTATION_GIZMO_GLB_PACKAGE[];
    extern int ROTATION_GIZMO_GLB_ROTATION_GIZMO_OFFSET;
    extern int ROTATION_GIZMO_GLB_ROTATION_GIZMO_SIZE;
}
#define ROTATION_GIZMO_GLB_ROTATION_GIZMO_DATA (ROTATION_GIZMO_GLB_PACKAGE + ROTATION_GIZMO_GLB_ROTATION_GIZMO_OFFSET)

#endif
