#!/usr/bin/env bash
#
# update_uberarchive_variants.sh
#
# Filament's gltfio ubershader provider is fed (UBERARCHIVE_DEFAULT_DATA,
# UBERARCHIVE_DEFAULT_SIZE). The DATA (UBERARCHIVE_PACKAGE[]) is linked from the
# per-platform uberarchive lib, but the SIZE constant is compiled from a header.
# Filament generates a PLATFORM-SPECIFIC uberarchive.h (different basis-compressed
# material archive per platform/backend), so a single vendored copy cannot match
# every platform's lib -- a size mismatch makes the basis transcoder throw
# "ArchiveCache: decompression failed: Src size is incorrect" at runtime.
#
# This script regenerates the per-platform variant headers + dispatch wrapper under
# thermion_dart/native/include/filament/{release,debug}/gltfio/materials/ by reading
# the authoritative UBERARCHIVE_DEFAULT_SIZE straight out of each platform's R2
# artifact (the exact zip thermion's build hook downloads and links), so the
# compiled size always matches the linked lib.
#
# Run after every Filament version bump. Requires: curl, python3.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

VERSION_FILE="$REPO_ROOT/filament.version"
if [ ! -f "$VERSION_FILE" ]; then
  echo "Error: $VERSION_FILE not found" >&2
  exit 1
fi
# filament.version format: "<repo> <version>" -- take the version (2nd field).
FILAMENT_VERSION="$(awk '{print $2}' "$VERSION_FILE")"
if [ -z "$FILAMENT_VERSION" ]; then
  echo "Error: could not read version from $VERSION_FILE" >&2
  exit 1
fi

R2_BASE="https://pub-c8b6266320924116aaddce03b5313c0a.r2.dev"

INCLUDE_ROOT="$REPO_ROOT/thermion_dart/native/include/filament"
PLATFORMS=(linux windows macos android)
MODES=(release debug)

# A generic uberarchive.h at native/include/filament/gltfio/materials/uberarchive.h
# (i.e. NOT under release/ or debug/) would resolve BEFORE the mode-specific copy
# because build.dart lists `native/include/filament` ahead of `.../filament/<mode>` in
# the include path. That shadows the mode-specific dispatch wrapper and silently
# re-introduces the size mismatch. Remove any such generic copy.
GENERIC_UBER="$INCLUDE_ROOT/gltfio/materials/uberarchive.h"
if [ -f "$GENERIC_UBER" ]; then
  echo "Removing shadowing generic uberarchive.h at $GENERIC_UBER"
  rm -f "$GENERIC_UBER"
fi

# Variant header template: only the size/offset constants. The dispatch wrapper
# (uberarchive.h) declares the extern UBERARCHIVE_PACKAGE[] and builds DATA from these.
write_variant() {
  local out="$1" platform="$2" mode="$3" size="$4"
  local guard
  guard="$(printf 'UBERARCHIVE_%s_%s_H_' "$(echo "$platform" | tr '[:lower:]' '[:upper:]')" "$(echo "$mode" | tr '[:lower:]' '[:upper:]')")"
  cat > "$out" <<EOF
// Auto-generated by scripts/update_uberarchive_variants.sh
// Source: filament-${FILAMENT_VERSION}-${platform}-${mode}.zip (gltfio/materials/uberarchive.h)
// Platform-specific basis-compressed ubershader archive size. Must match the
// UBERARCHIVE_PACKAGE[] bytes in the linked uberarchive lib for this platform+mode.
#ifndef ${guard}
#define ${guard}
#define UBERARCHIVE_DEFAULT_OFFSET 0
#define UBERARCHIVE_DEFAULT_SIZE ${size}
#endif
EOF
}

# Placeholder for platforms whose artifact isn't published yet (e.g. iOS on a fresh
# version bump). Fails loudly at compile rather than silently mis-sizing.
write_placeholder() {
  local out="$1" platform="$2" mode="$3"
  cat > "$out" <<EOF
// Auto-generated placeholder by scripts/update_uberarchive_variants.sh
// No filament-${FILAMENT_VERSION}-${platform}-${mode}.zip was available on R2.
// Build + publish that artifact, then re-run this script.
#ifndef UBERARCHIVE_PLACEHOLDER_H_
#define UBERARCHIVE_PLACEHOLDER_H_
#error "UBERARCHIVE: no ${platform}/${mode} variant. Publish filament-${FILAMENT_VERSION}-${platform}-${mode} and re-run scripts/update_uberarchive_variants.sh"
#endif
EOF
}

# Extract UBERARCHIVE_DEFAULT_SIZE from a downloaded zip. Uses python3 to read the
# uberarchive.h entry robustly (Windows zips use backslash separators; there are
# usually two copies -- include/gltfio/... and include/<mode>/gltfio/...).
extract_size() {
  local zip="$1"
  python3 - "$zip" <<'PY'
import sys, zipfile, re
z = zipfile.ZipFile(sys.argv[1])
for name in z.namelist():
    norm = name.replace("\\", "/")
    if norm.endswith("gltfio/materials/uberarchive.h"):
        data = z.read(name).decode("utf-8", "ignore")
        m = re.search(r"UBERARCHIVE_DEFAULT_SIZE\s+(\d+)", data)
        if m:
            print(m.group(1))
            sys.exit(0)
print("")
PY
}

for mode in "${MODES[@]}"; do
  outdir="$INCLUDE_ROOT/$mode/gltfio/materials"
  mkdir -p "$outdir"
  for platform in "${PLATFORMS[@]}"; do
    url="${R2_BASE}/filament-${FILAMENT_VERSION}-${platform}-${mode}.zip"
    zip="$(mktemp).zip"
    echo "Fetching $url"
    if curl -sS -f -L -o "$zip" "$url"; then
      size="$(extract_size "$zip")"
      rm -f "$zip"
      if [ -n "$size" ]; then
        write_variant "$outdir/uberarchive_${platform}.h" "$platform" "$mode" "$size"
        echo "  -> uberarchive_${platform}.h ($mode): UBERARCHIVE_DEFAULT_SIZE ${size}"
      else
        echo "  !! downloaded $url but could not find UBERARCHIVE_DEFAULT_SIZE; writing placeholder" >&2
        write_placeholder "$outdir/uberarchive_${platform}.h" "$platform" "$mode"
      fi
    else
      rm -f "$zip"
      echo "  -- $url not available; writing placeholder" >&2
      write_placeholder "$outdir/uberarchive_${platform}.h" "$platform" "$mode"
    fi
  done
done

# --- iOS: no separate iOS uberarchive artifact naming on R2 for this flow; placeholder. ---
# (When an iOS artifact is published, add "ios" to PLATFORMS above.)
for mode in "${MODES[@]}"; do
  outdir="$INCLUDE_ROOT/$mode/gltfio/materials"
  if [ ! -f "$outdir/uberarchive_ios.h" ]; then
    write_placeholder "$outdir/uberarchive_ios.h" "ios" "$mode"
    echo "  -> uberarchive_ios.h ($mode): placeholder (no iOS artifact)"
  fi
done

# --- Web: separate build/versioning (native/web/web.version). Preserve the value
# currently vendored so web behavior is unchanged until a web artifact is wired in. ---
for mode in "${MODES[@]}"; do
  outdir="$INCLUDE_ROOT/$mode/gltfio/materials"
  webfile="$outdir/uberarchive_web.h"
  if [ ! -f "$webfile" ]; then
    # Seed from whatever the (pre-conversion) vendored uberarchive.h carried, if present.
    seed="$(grep -oE 'UBERARCHIVE_DEFAULT_SIZE [0-9]+' "$outdir/uberarchive.h" 2>/dev/null | awk '{print $2}' || true)"
    seed="${seed:-0}"
    mode_up="$(echo "$mode" | tr '[:lower:]' '[:upper:]')"
    cat > "$webfile" <<EOF
// Auto-generated by scripts/update_uberarchive_variants.sh
// Web uses a separate build/versioning path (native/web/web.version). Seeded from the
// previously-vendored value (${seed}); update from the web build output if it diverges.
#ifndef UBERARCHIVE_WEB_${mode_up}_H_
#define UBERARCHIVE_WEB_${mode_up}_H_
#define UBERARCHIVE_DEFAULT_OFFSET 0
#define UBERARCHIVE_DEFAULT_SIZE ${seed}
#endif
EOF
    echo "  -> uberarchive_web.h ($mode): seeded with ${seed} (verify against web build)"
  fi
done

# --- Dispatch wrapper (identical for release and debug). The variant files alongside
# it supply the size; the wrapper selects one via compiler platform macros, which match
# the platform lib that build.dart links for the same target. ---
write_wrapper() {
  local out="$1"
  cat > "$out" <<'EOF'
// Auto-generated by scripts/update_uberarchive_variants.sh
//
// uberarchive.h is platform-specific: Filament generates a different basis-compressed
// ubershader archive per platform/backend, so UBERARCHIVE_DEFAULT_SIZE must match the
// UBERARCHIVE_PACKAGE[] bytes in the linked per-platform uberarchive lib. This wrapper
// selects the correct variant via the compiler's platform macro (which aligns with the
// lib chosen by build.dart for the same target). See scripts/update_uberarchive_variants.sh.
#ifndef UBERARCHIVE_H_
#define UBERARCHIVE_H_
#include <stdint.h>

extern "C" {
    extern const uint8_t UBERARCHIVE_PACKAGE[];
}

#if defined(_WIN32)
    #include "uberarchive_windows.h"
#elif defined(__APPLE__)
    #include <TargetConditionals.h>
    #if TARGET_OS_IPHONE
        #include "uberarchive_ios.h"
    #else
        #include "uberarchive_macos.h"
    #endif
#elif defined(__ANDROID__)
    #include "uberarchive_android.h"
#elif defined(__EMSCRIPTEN__)
    #include "uberarchive_web.h"
#elif defined(__linux__)
    #include "uberarchive_linux.h"
#endif

#ifndef UBERARCHIVE_DEFAULT_SIZE
    #error "UBERARCHIVE: no platform variant selected. Generate uberarchive_<platform>.h (scripts/update_uberarchive_variants.sh)."
#endif
#ifndef UBERARCHIVE_DEFAULT_OFFSET
    #define UBERARCHIVE_DEFAULT_OFFSET 0
#endif
#define UBERARCHIVE_DEFAULT_DATA (UBERARCHIVE_PACKAGE + UBERARCHIVE_DEFAULT_OFFSET)

#endif // UBERARCHIVE_H_
EOF
}

for mode in "${MODES[@]}"; do
  outdir="$INCLUDE_ROOT/$mode/gltfio/materials"
  write_wrapper "$outdir/uberarchive.h"
  echo "  -> uberarchive.h ($mode): dispatch wrapper"
done

echo "Done. Review changes under $INCLUDE_ROOT/{release,debug}/gltfio/materials/"
