name: example_cli
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.0

hooks:
  user_defines:
    thermion_dart: 
      mode: debug
      tracing: enabled

dependencies:
  thermion_dart: 
    path: ../../../thermion_dart

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.24.0
