#ifndef IMAGEMATERIAL_H_
#define IMAGEMATERIAL_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t IMAGEMATERIAL_PACKAGE[];
    extern int IMAGEMATERIAL_IMAGE_OFFSET;
    extern int IMAGEMATERIAL_IMAGE_SIZE;
}
#define IMAGEMATERIAL_IMAGE_DATA (IMAGEMATERIAL_PACKAGE + IMAGEMATERIAL_IMAGE_OFFSET)

#endif
