"""Present unmodified Cycles renders in an offline comparison viewer."""
from pathlib import Path
import argparse,base64,json,os
ROOT=Path(__file__).resolve().parent
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--renders',type=Path,default=ROOT/'samples/visible')
args=parser.parse_args();OUT=args.renders.resolve()
artifact_base=Path(os.path.relpath(OUT,ROOT)).as_posix()
images={name:'data:image/png;base64,'+base64.b64encode((OUT/f'{name}.png').read_bytes()).decode() for name in ['off','d0.6mm','d2mm']}
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>See subsurface scattering · Cycles</title>
<style>body{max-width:1480px;margin:32px auto;padding:0 24px;background:#121923;color:#e8eef6;font:16px system-ui;line-height:1.6}h1{font-size:30px;line-height:1.25}p{max-width:1030px}a{color:#9eccff}button,select{font:inherit;border:1px solid #61728a;border-radius:5px;color:inherit;background:#26384e;padding:9px 14px}button[aria-pressed=true]{background:#496b92}#controls{display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin:24px 0}#pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0}img{display:block;width:100%;height:auto}figcaption{padding:8px 0}#rightlabel{color:#ffcf9a}.where{position:relative;background:#202c3b;height:36px;font-size:14px}.where span{position:absolute;top:4px;transform:translateX(-50%);white-space:nowrap}.shadow{left:42%}.paint{left:71%}.note{border-left:3px solid #ffb96a;background:#1d2937;padding:12px 18px}#pair.blink{display:block;max-width:1050px}#pair.blink #reference{display:none}details{margin:20px 0}code{color:#ffcf9a}@media(max-width:760px){#pair{grid-template-columns:1fr}body{padding:0 12px}.where{font-size:12px}}</style>
<h1>Watch the shadow soften while the painted stripe stays sharp</h1>
<p>This is a close-up of a pale slab. An off-camera stencil casts the three dark “teeth” on the left. The straight dark stripe on the right is painted onto the surface. The light, camera, geometry and paint are identical in every render.</p>
<div id="controls"><label for="strength">SSS setting </label><select id="strength"><option value="d0.6mm">0.6 mm · smaller diffusion distance</option><option value="d2mm" selected>2 mm · exaggerated demonstration</option></select><button id="blink" aria-pressed="false">Alternate off / on</button><button id="hold">Hold to see off</button><span id="status" aria-live="polite"></span></div>
<div id="pair"><figure id="reference"><div class="where"><span class="shadow">Cast shadow ↓</span><span class="paint">Paint ↓</span></div><img id="left" alt="Cycles render with subsurface scattering off"><figcaption><strong>SSS off</strong> · hard-edged shadow</figcaption></figure><figure><div class="where"><span class="shadow">Cast shadow ↓</span><span class="paint">Paint ↓</span></div><img id="right" alt="Cycles render with subsurface scattering on"><figcaption id="rightlabel"></figcaption></figure></div>
<p class="note"><strong>Look inside the dark shadow around each tooth.</strong> With SSS on, light spreads into that region and the boundary gains a soft, reddish transition. The painted stripe retains a sharp edge. Red spreads farther here because its diffusion distance is larger than green’s and blue’s.</p>
<p>The 2 mm setting deliberately makes the effect obvious. Switch to 0.6 mm to see the smaller distance used for the earlier ball. This close-up spans 90 mm, and the hard shadow provides a much clearer signal than the ball’s smooth illumination. The paint stripe is 3 mm wide; each shadow tooth is 6 mm tall.</p>
<details><summary>Render settings and interpretation</summary><p>Actual Blender Cycles 4.5.0 Burley renders, 720 × 480, 1,024 samples per pixel, no denoising or sharpening. All images use the same Filament ACES display transform without per-image adjustments. The scene has a hard directional light, no environment illumination and no specular component, to isolate diffuse transport.</p><p>The stated millimeters are the Burley exponential diffusion distance d in red. Green and blue use half and one quarter of that distance. Cycles node radius × scale is set to 4πd, following the verified Cycles 4.5 conversion. These are synthetic demonstration materials, not a measured skin or wax preset. The interactive scene’s Blender display is Standard; exported PNGs use the shared ACES helper.</p><p>This viewer demonstrates Cycles. It does not establish Thermion agreement on this new scene. The earlier <a href="comparison-burley.html">matched Thermion/Cycles comparison</a> remains available.</p></details>
<p><a href="README.md#reproduction">Recreate the Blender scene</a> · <a href="render_sss_demonstration.py">Render script</a> · <a href="ARTIFACT_BASE/metadata.json">Settings and raw center rows</a> · Original PNGs: <a href="ARTIFACT_BASE/off.png">off</a> / <a href="ARTIFACT_BASE/d0.6mm.png">0.6 mm</a> / <a href="ARTIFACT_BASE/d2mm.png">2 mm</a></p>
<script>const images=IMAGES;const sel=document.getElementById('strength'),right=document.getElementById('right'),label=document.getElementById('rightlabel'),pair=document.getElementById('pair'),blink=document.getElementById('blink'),hold=document.getElementById('hold');let timer=null,on=true,holding=false;document.getElementById('left').src=images.off;function refresh(){const show=on&&!holding;right.src=images[show?sel.value:'off'];label.textContent=show?('SSS on · '+(sel.value==='d2mm'?'2 mm (exaggerated)':'0.6 mm')):'SSS off';document.getElementById('status').textContent=timer?(show?'On':'Off'):'';}sel.onchange=()=>{on=true;refresh()};blink.onclick=()=>{if(timer){clearInterval(timer);timer=null;on=true}else{on=true;timer=setInterval(()=>{on=!on;refresh()},1100)}pair.classList.toggle('blink',!!timer);blink.setAttribute('aria-pressed',String(!!timer));blink.textContent=timer?'Show side by side':'Alternate off / on';refresh()};hold.onpointerdown=e=>{holding=true;hold.setPointerCapture(e.pointerId);refresh()};hold.onpointerup=hold.onpointercancel=()=>{holding=false;refresh()};hold.onkeydown=e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();holding=true;refresh()}};hold.onkeyup=()=>{holding=false;refresh()};refresh();</script></html>'''
(ROOT/'visible-demo.html').write_text(html.replace('IMAGES',json.dumps(images)).replace('ARTIFACT_BASE',artifact_base))
print(ROOT/'visible-demo.html')
