# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Dart

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  thermion_dart:
    name: thermion_dart
    runs-on: macos-13
    defaults:
      run:
        working-directory: thermion_dart  # Adjust this path

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.26.0-0.1.pre'  # Specify Flutter version
          channel: 'master'          # or 'beta', 'dev', 'master'
          cache: true               # Caches dependencies between runs
          architecture: arm64         # Explicitly specify architecture
      - name: Install dependencies
        run: flutter pub get # even though this is a Dart package, it has as dev_dependency on objective_c for testing which for some reason has a Flutter dependency

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      #- name: Analyze project source
      #  run: dart analyze

      - name: Run tests
        run: dart --enable-experiment=native-assets test

  # thermion_flutter:
  #   name: thermion_flutter
  #   runs-on: macos-13
  #   defaults:
  #     run:
  #       working-directory: thermion_flutter/thermion_flutter  # Adjust this path

  #   steps:
  #     - uses: actions/checkout@v4
      
  #     - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

  #     - name: Install dependencies
  #       run: dart pub get

  #     # Uncomment this step to verify the use of 'dart format' on each commit.
  #     # - name: Verify formatting
  #     #   run: dart format --output=none --set-exit-if-changed .

  #     - name: Analyze project source
  #       run: dart analyze

  #     - name: Run tests
  #       run: dart --enable-experiment=native-assets test
