name: Dart/Flutter Tests and Example Apps

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dart-tests:
    uses: ./.github/workflows/run-dart-tests.yml

  flutter-builds:
    needs: dart-tests
    uses: ./.github/workflows/run-flutter-builds.yml
