// Auto-generated by scripts/update_uberarchive_variants.sh
//
// uberarchive.h is platform-specific: Filament generates a different basis-compressed
// ubershader archive per platform/backend, so UBERARCHIVE_DEFAULT_SIZE must match the
// UBERARCHIVE_PACKAGE[] bytes in the linked per-platform uberarchive lib. This wrapper
// selects the correct variant via the compiler's platform macro (which aligns with the
// lib chosen by build.dart for the same target). See scripts/update_uberarchive_variants.sh.
#ifndef UBERARCHIVE_H_
#define UBERARCHIVE_H_
#include <stdint.h>

extern "C" {
    extern const uint8_t UBERARCHIVE_PACKAGE[];
}

#if defined(_WIN32)
    #include "uberarchive_windows.h"
#elif defined(__APPLE__)
    #include <TargetConditionals.h>
    #if TARGET_OS_IPHONE
        #include "uberarchive_ios.h"
    #else
        #include "uberarchive_macos.h"
    #endif
#elif defined(__ANDROID__)
    #include "uberarchive_android.h"
#elif defined(__EMSCRIPTEN__)
    #include "uberarchive_web.h"
#elif defined(__linux__)
    #include "uberarchive_linux.h"
#endif

#ifndef UBERARCHIVE_DEFAULT_SIZE
    #error "UBERARCHIVE: no platform variant selected. Generate uberarchive_<platform>.h (scripts/update_uberarchive_variants.sh)."
#endif
#ifndef UBERARCHIVE_DEFAULT_OFFSET
    #define UBERARCHIVE_DEFAULT_OFFSET 0
#endif
#define UBERARCHIVE_DEFAULT_DATA (UBERARCHIVE_PACKAGE + UBERARCHIVE_DEFAULT_OFFSET)

#endif // UBERARCHIVE_H_
